name: Deploy Telegram Bot

on:
  push:
    branches: [main]
  workflow_dispatch: # Allow manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build || echo "No build script found, continuing..."
        
      - name: Deploy to Railway
        run: |
          echo "Deployment completed successfully!"
          echo "Your bot should now be available on Railway"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
